In [2]:
import numpy as np

In [3]:
salaries=np.genfromtxt('salary.csv',delimiter=',')

In [4]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [5]:
salaries.shape

(1147,)

In [6]:
#performing statistical operations

In [7]:
mean=np.mean(salaries)
median=np.median(salaries)
sd=np.std(salaries)
variance=np.var(salaries)

In [8]:
print(f"Mean={mean}\nMedian={median}\nStandard deviation={sd}\nVariance={variance}")

Mean=55894.53879686138
Median=48000.0
Standard deviation=55170.37550939316
Variance=3043770333.8474483


In [11]:
print('Mean=%i' %mean)
print('Median=%i'%median)
print('Start deviation=%i'%sd)
print('Variance=%i'%variance)

Mean=55894
Median=48000
Start deviation=55170
Variance=3043770333


In [12]:
#looping on numpy

In [13]:
a=np.arange(11)**2

In [14]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
for i in a:
    print(i**1/4)

0.0
0.25
1.0
2.25
4.0
6.25
9.0
12.25
16.0
20.25
25.0


In [16]:
b=np.arange(12)

In [17]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
for j in b:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [22]:
for j in b:
    print(j/2)

0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5


In [23]:
#looping through multi dimensional array

In [24]:
students=np.array([['hari','sai','krishna','dola'],
                  [35,67,98,54],
                  [301,302,303,304]])

In [25]:
for i in students:
    print('i=',i)

i= ['hari' 'sai' 'krishna' 'dola']
i= ['35' '67' '98' '54']
i= ['301' '302' '303' '304']


In [29]:
for b in students.flatten():
    print(b)

hari
sai
krishna
dola
35
67
98
54
301
302
303
304
